title: Terron Wright's Portfolio!
description: A small mess

#remote_theme: pages-themes/minimal@v0.2.0
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache